import { GoogleGenAI } from "@google/genai";
import { GeminiModel } from '../types';
import { fileToBase64 } from '../utils/fileHelpers';

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const makeApiCallWithRetry = async (apiCall: () => Promise<any>, retries = 2) => {
    for (let i = 0; i < retries; i++) {
        try {
            return await apiCall();
        } catch (error: any) {
            console.error(`API attempt ${i + 1} failed:`, error);
            
            // Check for Quota Exceeded (429) - Do not retry immediately, just throw specific error
            if (error?.status === 429 || error?.message?.includes('429') || error?.message?.includes('quota')) {
                 throw new Error("Lỗi Quota: API Key đã hết hạn ngạch sử dụng. Vui lòng đợi hoặc đổi Key khác.");
            }

            if (i === retries - 1) throw error;
            // Exponential backoff
            await delay(2000 * (i + 1));
        }
    }
};

// Helper function to fix common Python syntax errors generated by LLMs
const fixPythonSyntax = (code: string): string => {
    let fixed = code;
    // Fix 1: Unterminated string literals in ax.text/plt.text
    // Regex logic: Find text(..., r'$... <newline> ...$') and join them.
    // This is a heuristic and handles the specific error seen in logs.
    fixed = fixed.replace(/(\.text\([^)]*r'[^']*)\n\s*([^']*'\))/g, "$1$2");
    fixed = fixed.replace(/(\.text\([^)]*'[^']*)\n\s*([^']*'\))/g, "$1$2");
    return fixed;
};

export const analyzeImage = async (apiKey: string, file: File, modelId: string = GeminiModel.FLASH): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey });
  const base64Data = await fileToBase64(file);
  
  const prompt = `
  Bạn là một chuyên gia số hoá tài liệu giáo dục.
  Nhiệm vụ: Chuyển đổi hình ảnh đầu vào thành văn bản Markdown + LaTeX + Code Python minh hoạ.

  QUY TẮC BẤT KHẢ XÂM PHẠM:

  1. **VĂN BẢN & CÔNG THỨC (TEXT/MATH):**
     - **CHÉP NGUYÊN VĂN**: Chỉ xuất nội dung có trong ảnh. TUYỆT ĐỐI KHÔNG thêm lời dẫn meta (VD: "Đây là nội dung...", "Kết quả:", "Lời giải:", "--- Hết ---").
     - **KHÔNG** tự ý thêm tiêu đề bài viết nếu trong ảnh không có.
     - **LATEX**: Dùng $...$ cho toán học.
     - **MŨI TÊN**: Thay \`\\Longrightarrow\` thành \`\\Rightarrow\`, \`\\Longleftarrow\` thành \`\\Leftarrow\`.

  2. **VẼ HÌNH (QUAN TRỌNG - CHỈ DÙNG PYTHON):**
     - **MỤC TIÊU TỐI THƯỢNG**: Hình vẽ output phải có **GÓC NHÌN (PERSPECTIVE)** và **DÁNG VẺ** giống hệt ảnh gốc.
     - **Output code**: \`\`\`python ... \`\`\`.
     - **NẾU CÓ NHIỀU HÌNH**: Tách thành các block code Python riêng biệt. Đừng gộp chung.
     
     **Kỹ thuật Matplotlib bắt buộc:**
     - **Setup**: \`fig = plt.figure(figsize=(5, 5))\` (Giữ kích thước nhỏ gọn 5-6 inches).
     
     **A. NẾU LÀ HÌNH KHÔNG GIAN (3D - Hình chóp, Nón, Trụ, Cầu...):**
       - BẮT BUỘC dùng: \`ax = fig.add_subplot(111, projection='3d')\`.
       - **GÓC NHÌN CAMERA**: Phải dùng lệnh \`ax.view_init(elev=..., azim=...)\` để xoay hình cho KHỚP với ảnh gốc. Thử nghiệm các giá trị \`elev\` (độ cao) và \`azim\` (góc xoay) để tìm ra góc nhìn giống nhất.
       - Tắt khung 3D thừa nếu cần: \`ax.set_axis_off()\`.
       - Vẽ các cạnh khuất bằng nét đứt (\`linestyle='--'\`).

     **B. NẾU LÀ HÌNH PHẲNG (2D):**
       - Dùng \`ax = fig.add_subplot(111)\`.
       - **SAO CHÉP TỌA ĐỘ**: Đừng vẽ hình lý tưởng (VD: Tam giác đều chuẩn). Hãy nhìn ảnh gốc xem đỉnh A, B, C nằm ở đâu và ước lượng toạ độ \`(x, y)\` tương ứng để hình vẽ có độ nghiêng/dẹt giống hệt ảnh.
       - Dùng \`plt.axis('equal')\` và \`plt.axis('off')\` (nếu không phải đồ thị hàm số).
     
     **C. TRÁNH LỖI SYNTAX (CỰC KỲ QUAN TRỌNG):**
       - **KHÔNG NGẮT DÒNG TRONG STRING**: Tuyệt đối không để xuống dòng giữa chuỗi string trong lệnh \`text()\`.
         - ❌ SAI (Gây lỗi): 
           \`ax.text(x, y, r'$A\`
           \`$')\`
         - ✅ ĐÚNG: \`ax.text(x, y, r'$A$')\`
       - Hãy viết gọn label trên một dòng code duy nhất.

  3. **ĐỊNH DẠNG**:
     - Chỉ trả về Markdown. Không bọc trong JSON.
     - **CẤM**: Không viết thêm bất kỳ dòng chữ nào ngoài nội dung đề bài và code. Không "Lời giải", không "Kết luận".

  Hãy xử lý hình ảnh đính kèm:
  `;

  // Reduce thinking budget for Flash to 0 or low value to avoid "Resource Exhausted" (429) on free tier.
  // Flash is smart enough for this task without extensive thinking tokens.
  const isFlash = modelId.includes('flash');
  const budget = isFlash ? 1024 : 4096;

  return await makeApiCallWithRetry(async () => {
      const response = await ai.models.generateContent({
        model: modelId,
        contents: {
          parts: [
              { text: prompt },
              {
                  inlineData: {
                      mimeType: file.type,
                      data: base64Data
                  }
              }
          ]
        },
        config: {
          thinkingConfig: { thinkingBudget: budget } 
        }
      });

      let text = response.text || "";
      
      // Post-processing
      // 1. Fix common syntax errors in generated Python code BEFORE splitting
      text = fixPythonSyntax(text);

      const parts = text.split(/(```[\s\S]*?```)/g);
      text = parts.map(part => {
          if (part.startsWith('```')) return part;
          let p = part;
          p = p.replace(/\\Longrightarrow/g, '\\Rightarrow');
          p = p.replace(/\\Longleftarrow/g, '\\Leftarrow');
          p = p.replace(/\{aligned\}/g, '{align}');
          p = p.replace(/Figure/g, 'Hình');
          p = p.replace(/--- HẾT ---/gi, '');
          return p;
      }).join('');

      return text.trim();
  });
};

export const refineCode = async (apiKey: string, file: File, currentCode: string, modelId: string = GeminiModel.FLASH): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey });
  const base64Data = await fileToBase64(file);

  const prompt = `
  Nhiệm vụ: TINH CHỈNH CODE PYTHON ĐỂ HÌNH VẼ CÓ GÓC NHÌN (PERSPECTIVE) GIỐNG HỆT ẢNH GỐC.
  
  Mã hiện tại:
  \`\`\`python
  ${currentCode}
  \`\`\`

  Yêu cầu sửa đổi: 
  1. **GÓC NHÌN (Quan trọng nhất)**:
     - Nếu là 3D: Hãy chỉnh tham số \`ax.view_init(elev=..., azim=...)\` để xoay hình trùng khớp với hướng nhìn trong ảnh.
     - Nếu là 2D: Di chuyển toạ độ các điểm sao cho dáng hình (độ dẹt, độ nghiêng) khớp với ảnh.
  2. **TRÁNH LỖI SYNTAX**:
     - **KHÔNG ĐƯỢC NGẮT DÒNG TRONG STRING**: \`ax.text(..., r'abc')\` phải nằm trên 1 dòng.
     - Kiểm tra đóng mở ngoặc đầy đủ.
  3. **KỸ THUẬT**:
     - Giữ nguyên \`figsize\` hợp lý.
     - Đảm bảo code chạy được, import đầy đủ (matplotlib.pyplot as plt, numpy as np).

  Trả về duy nhất mã Python đã sửa trong block code.
  `;

  return await makeApiCallWithRetry(async () => {
    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [ { text: prompt }, { inlineData: { mimeType: file.type, data: base64Data } } ]
      },
      config: { thinkingConfig: { thinkingBudget: modelId.includes('flash') ? 1024 : 4096 } }
    });
    
    const text = response.text || "";
    const match = text.match(/```(?:python)?([\s\S]*?)```/);
    let code = match ? match[1].trim() : text.trim();
    
    // Apply syntax fix
    code = fixPythonSyntax(code);

    return code;
  });
};